"""change username > email in user model

Revision ID: 4373da11bbef
Revises: af1b6e0a5443
Create Date: 2022-03-30 17:11:26.245124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4373da11bbef'
down_revision = 'af1b6e0a5443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'username', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
