"""add picture_url to Blog

Revision ID: 6a7e806b478f
Revises: 68ab934057cf
Create Date: 2022-03-26 16:46:44.465767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7e806b478f'
down_revision = '68ab934057cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('picture_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'picture_url')
    # ### end Alembic commands ###
