"""delete password column

Revision ID: b734e6713161
Revises: 8affebb27cd4
Create Date: 2022-04-03 13:52:38.448715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b734e6713161'
down_revision = '8affebb27cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'password', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
