"""add column passwd

Revision ID: d04b907bb596
Revises: b734e6713161
Create Date: 2022-04-03 13:55:27.478406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04b907bb596'
down_revision = 'b734e6713161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwd', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passwd')
    # ### end Alembic commands ###
